version: "3.7"
services:
  db:
    image: postgres:latest
    ports:
      - "5452:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=3142
    volumes:
        - "dbdata:/var/lib/postgresql/data"
    restart: always
    networks:
        formulario:
  web:
    build: ./Backend/
    volumes:
      - ./Backend:/code
    ports:
      - "8005:8000"
    depends_on:
      - db
    restart: always
    networks:
        formulario:
  nginx:
    image: nginx:latest
    container_name: formulario_nginx
    ports:
      - "90:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./Frontend/build:/usr/src/app
    restart: always
    depends_on:
        - web
    networks:
      formulario:
  react:
    build: ./Frontend/
    container_name: frontend_formulario
    ports:
      - "3005:3000"
    volumes:
      - "./Frontend/public:/usr/src/app/public"
      - "./Frontend/src:/usr/src/app/src"
    restart: always
    networks:
        formulario:

networks:
  formulario:

volumes:
  dbdata: