# Generated by Django 3.2.4 on 2021-06-30 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormulariosModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_cliente', models.TextField(null=True, verbose_name='Id del cliente')),
                ('login_client', models.CharField(max_length=120, null=True, verbose_name='Nombre del Cliente')),
                ('contact', models.CharField(max_length=120, null=True, verbose_name='Por qué medio te contactaste?')),
                ('client_type', models.CharField(max_length=80, null=True, verbose_name='Tipo de Cliente')),
                ('stop_selling', models.CharField(max_length=80, null=True, verbose_name='Por qué dejó de comprar?')),
                ('order', models.CharField(max_length=50, null=True, verbose_name='Realizó un pedido?')),
                ('competition', models.CharField(max_length=50, null=True, verbose_name='Compra algún producto de la competencia')),
                ('seller_name', models.CharField(max_length=50, null=True, verbose_name='De quién compra')),
                ('product_details', models.CharField(max_length=120, null=True, verbose_name='Detalle del producto')),
                ('sample', models.CharField(max_length=50, null=True, verbose_name='Conseguiste una muestra?')),
                ('comment', models.CharField(max_length=300, null=True, verbose_name='Comentarios')),
                ('datetime_sent', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OptionsClientTypeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('options', models.CharField(max_length=80, verbose_name='Tipo de Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='OptionsCompetitionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('options', models.CharField(max_length=50, verbose_name='Compra algún producto de la competencia')),
            ],
        ),
        migrations.CreateModel(
            name='OptionsContactModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('options', models.CharField(max_length=120, verbose_name='Por qué medio te contactaste?')),
            ],
        ),
        migrations.CreateModel(
            name='OptionSellerNameModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('options', models.CharField(max_length=50, verbose_name='De quién compra')),
            ],
        ),
        migrations.CreateModel(
            name='OptionsOrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('options', models.CharField(max_length=50, verbose_name='Realizó un pedido?')),
            ],
        ),
        migrations.CreateModel(
            name='OptionsSampleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('options', models.CharField(max_length=50, verbose_name='Conseguiste una muestra?')),
            ],
        ),
        migrations.CreateModel(
            name='OptionsStopSellingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('options', models.TextField(verbose_name='Por qué dejó de comprar?')),
            ],
        ),
        migrations.CreateModel(
            name='UsuariosModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=120, verbose_name='Usuario')),
                ('contrasenia', models.CharField(max_length=120, verbose_name='Contraseña')),
            ],
        ),
    ]
