# Generated by Django 3.2.4 on 2021-07-27 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forms_manage', '0003_formulariosmodel_closed_sells'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulariosmodel',
            name='other_competition',
            field=models.CharField(max_length=200, null=True, verbose_name='Otro (compro algun producto de la competencia)'),
        ),
        migrations.AddField(
            model_name='formulariosmodel',
            name='other_seller',
            field=models.CharField(max_length=200, null=True, verbose_name='Otro (de quien compra)'),
        ),
        migrations.AddField(
            model_name='formulariosmodel',
            name='salesman_name',
            field=models.CharField(max_length=100, null=True, verbose_name='Nombre del vendedor'),
        ),
    ]
