# Generated by Django 3.2.4 on 2021-07-29 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Forms_manage', '0005_auto_20210727_1536'),
    ]

    operations = [
        migrations.RenameField('FormulariosModel', 'login_client', 'company')
    ]
