# Generated by Django 3.2.4 on 2021-07-29 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forms_manage', '0006_auto_20210729_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulariosmodel',
            name='company',
            field=models.CharField(max_length=120, null=True, verbose_name='Compañia'),
        ),
    ]
