# Generated by Django 3.2.4 on 2021-07-05 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forms_manage', '0002_auto_20210702_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulariosmodel',
            name='closed_sells',
            field=models.CharField(max_length=120, null=True, verbose_name='Cerraste alguna venta?'),
        ),
    ]
