# Generated by Django 3.2.4 on 2021-07-27 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forms_manage', '0004_auto_20210727_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulariosmodel',
            name='closed_sells',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Cerraste alguna venta?'),
        ),
        migrations.AlterField(
            model_name='formulariosmodel',
            name='comment',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Comentarios'),
        ),
        migrations.AlterField(
            model_name='formulariosmodel',
            name='competition',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Compra algún producto de la competencia'),
        ),
        migrations.AlterField(
            model_name='formulariosmodel',
            name='other_competition',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Otro (compro algun producto de la competencia)'),
        ),
        migrations.AlterField(
            model_name='formulariosmodel',
            name='other_seller',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Otro (de quien compra)'),
        ),
        migrations.AlterField(
            model_name='formulariosmodel',
            name='product_details',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Detalle del producto'),
        ),
        migrations.AlterField(
            model_name='formulariosmodel',
            name='salesman_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre del vendedor'),
        ),
        migrations.AlterField(
            model_name='formulariosmodel',
            name='sample',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Conseguiste una muestra?'),
        ),
        migrations.AlterField(
            model_name='formulariosmodel',
            name='seller_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='De quién compra'),
        ),
        migrations.AlterField(
            model_name='formulariosmodel',
            name='stop_selling',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Por qué dejó de comprar?'),
        ),
    ]
